### ISSUE TITLE
"MAV" when using a newer compiler than MinGW 7.5?!

### ISSUE THREAD

**Issue by GrisuBMX** [davecamp/FModEncoder#3]
Hi Dave,
I wasn't sure, if you were still here. :)

I'm still using your Fmod encoder for my Pocket Radio Player app. In newer releases I make use MinGW 7.5 (Win32).
Recently I wanted to update my compiler to a newer main branch version. The GCC packages I use are from Brecht Sanders: https://github.com/brechtsanders/winlibs_mingw/releases

Everything runs fine apart from the recording/encoder part: 
- With "OGG" and "WAV" no output file is created. 
- With "MP3" I get an "EXEPTION_ACCESS_VIOLATON" and the app crashes.

I also tested the issue with different compliers ranging from GCC 8.x to 10.x with same results.

Strangely, everything works out as expected when I compile my with bmx "debug mode on"! The issue is reproducable with your "example.bmx" code too.

It would be great, if you could fix this.
Stefan

P.S.: 
I updated the encoder with the latest fixes from xiph.org (libvorbis -> 1.3.7 (20704) and libogg 1.3.4 (190830) ).
I can share these, if you want. The issue above is independent from that.

**Comment by davecamp** [comment]
Hiya Grisu.

I've just seen this from a post in SyntaxBomb. My apologies for not responding already.

Specifically which gcc package are you using from the link that you've mentioned? And yes, if you could share the latest ogg vorbis libs (just a link be ok) that would be great. Also which version of BMax are you working with?

**Comment by GrisuBMX** [comment]
Hi, 
no need to apologize. I'm glad that there are still people out there supporting BMX.

I temporarily uploaded my whole BMX folder with all modules, so you can grab my changes. (removed link)

Using mostly "BMX Vanilla" (32 Bit). Still can't get Brucey's version to work properly.
For the ogg / vorbis part, I updated the mod with the files from: https://xiph.org/downloads/

For GGC versions used, I switched to the ones from Brecht Sanders I got in contact with. He compiled a GCC 7.5 build for me.

Newer versions, that don't work, are for instance...
GCC 11.1: https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.1.0-8.0.0-r2
GCC 10.1: https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.1.0-7.0.0-r1
GCC 9.3: https://github.com/brechtsanders/winlibs_mingw/releases/tag/9.3.0-7.0.0-r2
GCC 8.4: https://github.com/brechtsanders/winlibs_mingw/releases/tag/8.4.0-7.0.0-r1

I always use the "i686-posix" builds = (32 Bit) versions.

Wasn't able to "track" the error, as the encoder works fine in "debug mode". The exe is 2x the size and slower. So I don't want that as a release build. :) - My wild guess is that there are some Null-pointers that cause the issue.

If I can assist further, please let me know.

**Comment by davecamp** [comment]
I agree that you shouldn't use a debug build in place of a release - something's wrong if you need to do that.
I think you're suggestion is in the correct area - maybe not a null pointer but some 'out of date' instance of an object. In release builds this will show up as an error (crash) but for debug builds the debugger will hold a reference to an object for longer hiding the real issue.

Taking a look now...

**Comment by davecamp** [comment]
I can't get this to compile as I get a '`__sync_bool_compare_and_swap' not found error in one of my files.
I've also tried with your personal version linked above.

Do you not get the same?

**Comment by GrisuBMX** [comment]
Which GCC you use? 
With 8.x and 9.x. Get no such errors.

**Comment by davecamp** [comment]
8.4

Lets start from scratch as I'm rusty with this kind of installation with BMax.

I have this setup for MinGW-

D:\MinGW8.4\
...bin\
...i686-w64-mingw32\
..include\
...lib\
...libexec\
...share\

For BlitzMax I'm using your installation linked above so all modules are already in place -
D:\GrisuBmax\BlitzMax\
...bin\
...cfg\
[......]
MaxIDE.exe
MaxIDE2.exe
[......]

Set the Environment variable:
MinGW as D:\MinGW8.4

And added to Path
D:\MinGW8.4\bin

In a command line for gcc --version I get:
gcc (MinGW-W64 i686-posix-dwarf, built by Brecht Sanders) 8.4.0

I hit 'rebuild all modules' and get that error. Hmm.

**Comment by davecamp** [comment]
I can see potential pointer arithmetic bugs in there that would actually prevent compilation in Visual Studio (with an appropriate error of course), so I'll fix those up once I get it compiling.

**Comment by davecamp** [comment]
I seem to remember having to copy some stuff into the BlitzMax\libs\ folder years ago. Is that not the case any more?

**Comment by GrisuBMX** [comment]
You don't have to do this afaik,

I place my GCC build inside:
C:\MinGW\mingw32

And hit "rebuild all modules".

Just did so with 8.4, no error messages. My app runs fine.. :/

**Comment by davecamp** [comment]
Lol. Closing and reloading the MaxIDE.exe worked to pickup any changes I made to the environment variables.
Back to working on the original issue...

**Comment by davecamp** [comment]
Could you download and try the latest version. I found an issue with the mp3 encoder - I would have expecting a compiler error but ho hum.

It encodes with all encoders now in debug and release for me. Tested with the MinGW 9.3 installation linked above.

**Comment by davecamp** [comment]
Oh, and I updated the vorbis and ogg versions to the ones from your installation.

**Comment by GrisuBMX** [comment]
Awesome!
From my early testing it seems to work.

Will open a new report, if need be. Need more time on this. But you can close the thread. :)

**Comment by davecamp** [comment]
Sounds good to me 👍
